// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGV-gbWdW8cqczBDNdhfgkGdgfBRwC4b4',
    appId: '1:7535639430:web:27c281c01470a7816b8a07',
    messagingSenderId: '7535639430',
    projectId: 'fir-flutter-codelab-2d6de',
    authDomain: 'fir-flutter-codelab-2d6de.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-2d6de.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpZNYBsHUFLbeDSrO9lJUvJfW40QNv57U',
    appId: '1:7535639430:android:9793f59d6b1cab896b8a07',
    messagingSenderId: '7535639430',
    projectId: 'fir-flutter-codelab-2d6de',
    storageBucket: 'fir-flutter-codelab-2d6de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4HgSXNzBuuimV3qc_LUCVtrr-zeDmY9I',
    appId: '1:7535639430:ios:e38ac252592976026b8a07',
    messagingSenderId: '7535639430',
    projectId: 'fir-flutter-codelab-2d6de',
    storageBucket: 'fir-flutter-codelab-2d6de.appspot.com',
    iosClientId: '7535639430-gkllno0cmatqrbr6hl48ps7bsph7s3f2.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4HgSXNzBuuimV3qc_LUCVtrr-zeDmY9I',
    appId: '1:7535639430:ios:e38ac252592976026b8a07',
    messagingSenderId: '7535639430',
    projectId: 'fir-flutter-codelab-2d6de',
    storageBucket: 'fir-flutter-codelab-2d6de.appspot.com',
    iosClientId: '7535639430-gkllno0cmatqrbr6hl48ps7bsph7s3f2.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
